### ISSUE TITLE
whitelist/blacklist function

### ISSUE THREAD

**Issue by DrJekyllH** [The-Zandrax/NoMoreCooked#26]
**Is your feature request related to a problem? Please describe.**
Some items already created in Itemsadder are not suitable for setting expiration.

**Describe the solution you'd like**
Need whitelist/blacklist for foods with expiration function.

**Describe alternatives you've considered**
- enable-fresh-food-expiration: false
 
I disabled the expiration for all fresh food because it is not possible to disable it for only tropical fish custom data items.
However, this solution does not enable the essential functionality of the plugin, so I am hesitant to deploy this plugin on my server.

**Additional context**
It would be great if it could be specified whether or not the expiration feature is allowed by specifying the data number of the custom model.

**Comment by The-Zandrax** [comment]
If I understand correctly, you'd like to be able to define a list of items for which you don't want expiration system ? 

![image](https://github.com/user-attachments/assets/65322634-11ce-4538-89cf-784dc43eae70)

So the item in the list with this custom model data would not be affected by the expiration system ?

**Comment by DrJekyllH** [comment]
Yes! like that!

**Comment by The-Zandrax** [comment]
Perfect, I'm working on it today

**Comment by The-Zandrax** [comment]
A functional blacklist has been implemented in **version 0.0.99 of NoMoreCooked**, available on Spigot. 

Here's how it looks, and its position in the configuration _(just below itemsAdder support activation)_

![image](https://github.com/user-attachments/assets/f82ff9ec-1239-47ac-9d7f-080dfb8e2c1d)

Have a nice day !

**Comment by DrJekyllH** [comment]
Thank you. I tried it immediately.
Unfortunately, it does not seem to be working.
For example, my certain Itemsadder Item (custom fishing fish) is assigned to TROPICAL_FISH:10000.
I have listed it on my Blacklist. When I actually caught the fish, the expiration was displayed in Lore.
Could this be a compatibility issue with the custom fishing plugin?

LiteFish-4.7.0
NoMoreCooked-0.0.99-RELEASE
Paper 1.21
![image](https://github.com/user-attachments/assets/d4dd5b14-27eb-4a2e-ac6d-62e55889241c)

**Comment by The-Zandrax** [comment]
I'm sorry to hear that there's a problem. 

However I don't think it's due to a compatibility problem between plugins, I think rather that the method called doesn't go through a blacklist check.

**Could you run the following test :** 

1.  Take one of your fish added to the blacklist with the IA menu or via the /iaget command so that the fish is not affected by the expiration system
2. Throw the fish on the ground 
3. Pick up the fish again
4. Check if the fish is affected by the expiry system once picked up

Thanks in advance

**Comment by DrJekyllH** [comment]
Thank you for your replayThanks for the reply.
I have tried 1 to 4.
Items were not affected by the expiration date system.
More to the point, foods that were not blacklisted were also not affected by the expiration date system.

**Comment by The-Zandrax** [comment]
So there's a problem specific to your environment. 

In the tests I've just redone, the blacklist works correctly for item pickup.

I've also tested with litefish, and the blacklist works correctly.

For problem number one, which concerns the blacklist not working when you pick up an item, could you share your NoMoreCooked config.yml? 

For problem number two, which concerns litefish, I think the problem comes from the fact that when you added your fish via the GUI, it was subject to an expiry date, so now every time the fish is caught, it has an expiry date. At least, that's what I noticed during my tests. I invite you to replace your fish with virgin fish that don't have expiry dates and to repeat the tests.

It's also possible that problem number two is linked to problem number one, so I'm waiting for your configuration file so that I can go further in detecting the problem. 

What's reassuring is that I've come up with a positive result for both, but I've also gone through a negative result for both, so a solution is possible.

**Comment by DrJekyllH** [comment]
Regarding the second issue you mentioned, I don't think it is possible. I think it is unlikely, because I have been using litefish since before the NMC was installed. And now, encountering the NMC and trying to install it, I faced this problem for the first time.

Anyway, I am a little relieved that there is hope for a solution.
The config file is attached.
Please check it.
[config.txt](https://github.com/user-attachments/files/17432824/config.txt)

**Comment by The-Zandrax** [comment]
For the blacklist, I see that you haven't activated it. You need to change `enable-blacklist: false` to `enable-blacklist: true`. I've done it for you.

You've also deactivated `enable-fresh-food-expiration`, which explains why other foods when you pick them up are not affected. I've changed it to `true`, you're free to deactivate it again, but if I understand correctly, you want it activated.

Another thing, I see that you've added `#` in front of some of the items in the fresh foods list, I'd recommend that you put `-1` like I did to disable expiration for an item. You can set an expiration time if you want expiration to apply to these items, which I'm assuming you want to do given the blacklist. So I've just set an expiry time for `TROPICAL_FISH` so that you can see that the blacklist works.

I can also see that the configuration is a bit damaged after the config update, so I've redone a clean one for you, keeping your settings _(except those mentioned above)_ but putting some options in the right place. 

[config.txt](https://github.com/user-attachments/files/17434387/config.txt)

Let me know if this solves your problems.

**Comment by DrJekyllH** [comment]
Thank you very much.
I seem to have sent you a configuration file during various trial and error attempts. Sorry about that.

I tried with the configuration file you shared me, but things are still the same. It seems that there is a conflict with some other plugin.

-1! I didn't know that was possible. To be honest, I thought that would be fine for a while.
In any case, I'll try to find time to see what it's conflicting with.

**Comment by The-Zandrax** [comment]
Okay, because the configuration sent should indeed work. 

As a further step towards defining the cause of the problem, you can simply leave NoMoreCooked, LiteFish and ItemsAdder on the server and run the tests to ensure that the error is no longer configuration-related. 

If everything works as expected, you can add others plugins as you go along to find out which one is responsible for the conflict, and then either contact the developer of the conflicting plugin yourself, or give me the information so I can work out a solution with the developer. 

If you have any console errors, please let me know. 

For the -1, it's a logic I've implemented, I don't recommend this operation for all other plugins not knowing how the plugin would react. 

In any case, I'll be happy to help if you need any further assistance in the future.

**Comment by DrJekyllH** [comment]
I tried running the server with your modified configuration file and the minimum configuration plugin.
However, it still shows the expiration date.

Next, I replaced the litefish fish again with one obtained from /iaget.
The expiration date still appears on the fish.

The expiration date is displayed when I drop the material obtained with /iaget on the ground. This material custom model data is blacklisted. Is this behavior correct?
I think that the expiration date should not be displayed since the item is in the blacklist...

Server
- paper 1.21

Installed plugins
- ItemsAdder_4.0.2-beta-release-12
- LiteFish-4.7.1
- LoneLibs
- NoMoreCooked-0.0.99-RELEASE
- ProtocolLib

[config.txt](https://github.com/user-attachments/files/17442712/config.txt)

**Comment by The-Zandrax** [comment]
Indeed, you're right, the configuration I sent you doesn't behave as expected. I've just used it in the same environment as you, and the problem occurs. 

Yesterday I managed to solve the problem, so I'm trying to find out which option in the configuration breaks everything, and I'll get back to you as soon as I've found a solution.

**Comment by The-Zandrax** [comment]
I found the problem, the configuration had nothing to do with it, it was in fact a problem with the format of the Blacklist, it could only handle one custom model data per item, now it can handle as many as required. 

Update 0.1 of NoMoreCooked, to be released shortly, will implement the fix.

**Comment by DrJekyllH** [comment]
Thank you very much.
I look forward to trying 0.1.

Also, apart from this, I've been touching around with the plugin and have come up with a few ideas for features that you might be interested in.
I will discuss them with you again at some point.

**Comment by The-Zandrax** [comment]
**Version 0.1 of NoMoreCooked has been released on Spigot** with new features and the blacklist fix, so let me know if the blacklist issue has been resolved for you ! 

As for ideas for improving the plugin, I'm open to all proposals, and I appreciate your willingness to improve it

**Comment by DrJekyllH** [comment]
I tried 0.1.
It seems to be working well!
I tried 0.1.
It seems to be working well!
My only concern is that there was an error in the process of converting the data to the new format.
I checked and found that the conversion was not successful in the following areas

old file
```
# Date and time format in item lore
date-format: "yyyy年MM月dd日HH:mm" # Preferred date format
hour-format: "HH:MM:SS" # Preferred time format
```

new file
```
# Date and time format in item lore
date-format: "yyyy年MM月dd日HH
hour-format: "HH:mm:ss" # Preferred time format
```
This may have happened because HH:mm was not assumed as the date-format.

I will find time after tomorrow to check for errors in a production-like environment.

**Comment by The-Zandrax** [comment]
That's because it had to recover the colon of the value as a key-value separator and it didn't handle the case well because it wasn't foreseen in the auto-conversion method

I had anticipated the hour-format but not the date-format

I'm going to remove the deletion of the old configuration after conversion to avoid losing the old values if this happens

I'm also going to ignore the date-format for the moment in the automatic conversion

Version 0.1.1 implements the above elements

i'll add colon management to the values a little later

Glad to hear the blacklist now works for you !
